#!/usr/bin/env dash
MODKEY=Mod4
xrandr --output VGA-0 --left-of DVI-0
xrandr --output VGA-0 --auto
xrandr --output VGA-0 --left-of DVI-0

# tagrules
wmiir write /tagrules <<!
/trayer|panel|VLC.*|MPlayer.*/ -> +/^/+~
/terminal|Firefox|nautilus/ -> sel
/main.py/ -> ~
/Thunderbird|empathy/ -> communication
/rhythmbox/ -> music
!

local_events() {
	cat << EOF
Key $MODKEY-n
	nautilus --no-desktop&

KeyGroup Multimedia
Key XF86AudioLowerVolume
	vol down
Key XF86AudioRaiseVolume
	vol up
Key XF86AudioMute
	vol mute

KeyGroup Resize Windows
Key $MODKEY-Control-$UP
	echo -n "grow sel sel down -1" | wmiir write /tag/sel/ctl
Key $MODKEY-Control-$RIGHT
	echo -n "grow sel sel right 1" | wmiir write /tag/sel/ctl
Key $MODKEY-Control-$DOWN
	echo -n "grow sel sel down 1" | wmiir write /tag/sel/ctl
Key $MODKEY-Control-$LEFT
	echo -n "grow sel sel right -1" | wmiir write /tag/sel/ctl
EOF
}

# load at startup
pgrep gnome-settings- || gnome-settings-daemon &

killall trayer
trayer --width 4 --edge top --height 16 --transparent true --alpha 255&

pgrep hamster-service || hamster-time-tracker&
pgrep hamster-indicat || hamster-indicator&
pgrep pomodoro-indica || pomodoro-indicator&
pgrep gnome-fallback- || /usr/lib/gnome-settings-daemon/gnome-fallback-mount-helper&
pgrep nm-applet || nm-applet&
pgrep gnome-sound-app || gnome-sound-applet&

eval $(gnome-keyring-daemon --start)
