#!/usr/bin/env dash
MODKEY=Mod4
xrandr --output VGA-0 --left-of DVI-0
xrandr --output VGA-0 --auto
xrandr --output VGA-0 --left-of DVI-0

# tagrules
wmiir write /tagrules <<!
/trayer|panel|VLC.*|MPlayer.*/ -> +/^/+~
/terminal|Firefox|nautilus/ -> sel
/main.py/ -> ~
/Thunderbird|empathy/ -> communication
/rhythmbox/ -> music
!
